version: '3'
services:
  messages_backend:
    container_name: messages_backend
    image: messages_backend_image
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8001:4000'
    volumes:
      - ./:/app
      - exclude:/app/node_modules/
    command: npm start
volumes:
    exclude: