version: '3.9'
services:
  sacms-backend:
    container_name: chat-backend
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    volumes:
      - ./:/app
      - exclude:/app/node_modules/
    command: npm start
volumes:
    exclude: